[project]
name = "spec-rrv"
version = "0.1.0"
description = "Practice for specialist.ru-flask1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
